name: Actualizar RSS BOPA

on:
  schedule:
    - cron: '0 7 * * *' # 7 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar script
      run: python main.py

    - name: Verificar y Guardar cambios
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        
        # Solo intentamos añadir si el archivo existe
        if [ -f feed.xml ]; then
          git add feed.xml
          # Commit solo si hay cambios reales
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar feed RSS" && git push)
        else
          echo "Error: feed.xml no fue generado."
          exit 1
        fi
